### ISSUE TITLE
4 out of 6 integration test cases failed

### ISSUE THREAD

**Issue by TrapdoorHeader** [appliedzkp/zkevm-circuits#392]
I run the integration tests as specified in the `run.sh`.  The `gendata_output.json` generated by running `gen_blockchain_data` is attached below. And I tried the `circuits` test cases which have 4 of 6 failed. The detailed log is reproduced here.

```
running 6 tests
[2022-03-16T09:57:11Z DEBUG reqwest::connect] starting new connection: http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::connect] starting new connection: http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::connect] starting new connection: http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::connect] starting new connection: http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::connect] starting new connection: http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::connect] starting new connection: http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODESIZE
[2022-03-16T09:57:11Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
[2022-03-16T09:57:11Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-03-16T09:57:11Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z DEBUG reqwest::async_impl::client] response '200 OK' for http://localhost:8545/
[2022-03-16T09:57:11Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODESIZE
[2022-03-16T09:57:11Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
[2022-03-16T09:57:11Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-03-16T09:57:11Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
thread 'test_evm_circuit_block_deploy_greeter' panicked at 'not implemented', zkevm-circuits/src/evm_circuit/witness.rs:1182:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test_evm_circuit_block_deploy_greeter ... FAILED
thread 'test_state_circuit_block_transfer_0' panicked at 'assertion failed: self.current_region.is_none()', /home/xkx/.cargo/git/checkouts/halo2-b8251ca10f182e2b/90f0487/halo2_proofs/src/dev.rs:506:9
test test_state_circuit_block_transfer_0 ... FAILED
thread 'test_state_circuit_block_deploy_greeter' panicked at 'assertion failed: self.current_region.is_none()', /home/xkx/.cargo/git/checkouts/halo2-b8251ca10f182e2b/90f0487/halo2_proofs/src/dev.rs:506:9
thread 'test_state_circuit_block_multiple_transfers_0' panicked at 'assertion failed: self.current_region.is_none()', /home/xkx/.cargo/git/checkouts/halo2-b8251ca10f182e2b/90f0487/halo2_proofs/src/dev.rs:506:9
test test_state_circuit_block_multiple_transfers_0 ... FAILED
test test_state_circuit_block_deploy_greeter ... FAILED
test test_evm_circuit_block_multiple_transfers_0 has been running for over 60 seconds
test test_evm_circuit_block_transfer_0 has been running for over 60 seconds
test test_evm_circuit_block_transfer_0 ... ok
test test_evm_circuit_block_multiple_transfers_0 ... ok

failures:

failures:
    test_evm_circuit_block_deploy_greeter
    test_state_circuit_block_deploy_greeter
    test_state_circuit_block_multiple_transfers_0
    test_state_circuit_block_transfer_0

test result: FAILED. 2 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 71.38s

```

**Comment by TrapdoorHeader** [comment]
okay.

**Comment by lispc** [comment]
for those who searched and went here, "self.current_region.is_none()" is a quite confusing error message. The reason for that message is that we are assigning unavailable rows, say there are 1024 rows and we are assigning the last several blinding rows.
