### ISSUE TITLE
testnet: Call stack is empty but call is used

### ISSUE THREAD

**Issue by pinkiebell** [appliedzkp/zkevm-circuits#431]
Run the following command inside the zkevm-chain repo to reproduce:
`docker run --pull --rm -v $(pwd):/host -e 'RUST_BACKTRACE=1' -e 'RPC_URL=https://zkevmchaingeth1.efprivacyscaling.org/rpc/l2' -e 'BLOCK_NUM=1' -e 'PARAMS_PATH=/host/params' --entrypoint /prover_cmd ghcr.io/appliedzkp/zkevm-chain/coordinator:latest`

####### output

```sh
[2022-04-06T09:30:50Z WARN  bus_mapping::circuit_input_builder] This does not look like a EIP-1559 block - base_fee_per_gas defaults to zero
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode STATICCALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode STATICCALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode LOG3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode LOG3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode LOG3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode LOG3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode LOG3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode DELEGATECALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode STATICCALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode STATICCALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode STATICCALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
thread 'main' panicked at 'gen_inputs for BLOCK_NUM: InvalidGethExecTrace("Call stack is empty but call is used")', prover/src/bin/prover_cmd.rs:65:10
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d914f17ca71a33a89b2dc3436fca51b1a091559e/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at ./rustc/d914f17ca71a33a89b2dc3436fca51b1a091559e/library/core/src/panicking.rs:106:14
   2: core::result::unwrap_failed
             at ./rustc/d914f17ca71a33a89b2dc3436fca51b1a091559e/library/core/src/result.rs:1613:5
   3: prover_cmd::main::{{closure}}
   4: tokio::park::thread::CachedParkThread::block_on
   5: tokio::runtime::thread_pool::ThreadPool::block_on
   6: tokio::runtime::Runtime::block_on
   7: prover_cmd::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pinkiebell** [comment]
@han0110 Could this be related with ExecutionState::[CALL,STOP] like #419 ?

**Comment by han0110** [comment]
Ah I have just found the issue, it's because `STATICCALL` and `DELEGATECALL` is used, and they are not implemented yet, so their call is not parsed and push to call stack properly.

I am trying to make a dummy handler to at least parse the call to make the `CircuitInputBuilder` work.

**Comment by CPerezz** [comment]
This is weird. As the panic message refers to `BLOCK_NUM`. Is it refering to `NUMBER` opcode? Or it should appear some variable? It's a really weird panic message description.

**Comment by barryWhiteHat** [comment]
@icemelon why did you close this issue ?

**Comment by HAOYUatHZ** [comment]
> @icemelon why did you close this issue ?

I think @han0110 link #434 to this issue and says #434 can resolve this.
Once #434 is merged, this issue is automatically closed.

Because it's @icemelon who merged this, so it shows @icemelon closed this issue.

**Comment by HAOYUatHZ** [comment]
> @icemelon why did you close this issue ?

I think @han0110 link #434 to this issue and says #434 can resolve this.
Once #434 is merged, this issue is automatically closed.

Because it's @icemelon who merged this, so it shows @icemelon closed this issue.

**Comment by barryWhiteHat** [comment]
Ah cool. Understood :)
