### ISSUE TITLE
`MLOAD` paniks for memory positions bigger than 692224

### ISSUE THREAD

**Issue by adria0** [appliedzkp/zkevm-circuits#521]
Works ok with `692224`

```
PUSH3(692224)
MLOAD
STOP
Execution result is : Ok(())
```

but fails with the next one...

```
PUSH3(692225)
MLOAD
STOP
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', bus-mapping/src/evm/opcodes/mload.rs:36:30
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: <bus_mapping::evm::opcodes::mload::Mload as bus_mapping::evm::opcodes::Opcode>::gen_associated_ops
   4: bus_mapping::evm::opcodes::gen_associated_ops
   5: bus_mapping::circuit_input_builder::CircuitInputBuilder::handle_block
   6: zkevm_circuits::test_util::run_test_circuits
   7: evm_testvectors::main
```

**Comment by CPerezz** [comment]
oh.... 
So I tried to write a test that interacts directly with the Memory struct.

```rust
 #[test]
    fn issue_521_test() {
        let mem = Memory(vec![]);

        let res = mem.read_chunk(MemoryAddress::from(692225u32), MemoryAddress::from(32u8));
        assert_eq!(res, vec![0; 32])
    }
```

This passes the test correctly. So basically we are indeed getting the 32 0's that we expect. 
It also does for `0x620a90015100u64` or any other value like `u64::MAX`.

Extending the tests to `read_word` which calls `read_chunk` it also doesn't cause any errors on the read reporting an empty word as result:
```rust
#[test]
    fn issue_521_test() {
        let mem = Memory(vec![]);

        let res = mem.read_word(MemoryAddress::from(692224u32));
        assert_eq!(res, Word::zero());

        let res = mem.read_word(MemoryAddress::from(692225u32));
        assert_eq!(res, Word::zero())
    }
```

At this point is quite clear that the error is not in the Memory implementation but rather on how do we handle a block.

To check it, I did a test that executes this and runs the `handle_block` function in the tests.
See:
```
let code = bytecode! {
            .setup_state()

            PUSH3(0x692225u64)
            MLOAD
            STOP
        };

        // Get the execution steps from the external tracer
        let block: GethData = TestContext::<2, 1>::new(
            None,
            account_0_code_account_1_no_code(code),
            |mut txs, accs| {
                txs[0]
                    .from(accs[1].address)
                    .to(accs[0].address)
                    .gas_price(Word::zero());
            },
            |block, _tx| block.base_fee_per_gas(Word::zero()),
        )
        .unwrap()
        .into();

        let mut builder = BlockData::new_from_geth_data(block.clone()).new_circuit_input_builder();
        builder
            .handle_block(&block.eth_block, &block.geth_traces)
            .unwrap();
```

And this is the result: 
```
thread 'evm::opcodes::mload::mload_tests::mload_opcode_impl_512' panicked at 'reversion_groups should not be empty for non-persistent call', bus-mapping/src/circuit_input_builder/input_state_ref.rs:154:18
```
 
This is failing after calling `gen_begin_tx_ops`. After this fn is called, it calls into `transfer_with_fee`. And this one, reports an error about having an empty reversion_group. Which is nonsensical TBH. As `transfer_with_fee` calls twice `push_op_reversible`.

The first call is to add an `Operation` related to the sender's balance change. But nothing seems to be wrong there.

I'll need to further investigate it!

**Comment by CPerezz** [comment]
kk nevermind all I did. 
I fixed a chain of errors which ends up at the fact that Geth retunrs an out-of-gas for the execution of this bytecode.

That's why I get now a subtraction overflow on the `end_tx` fn call.

The problem is that I don't understand why if there's an `out_of gas` error it's not seen by the code and a revert is thrown.

**Comment by CPerezz** [comment]
I was wondering that. But our impl is not catching it. 

The thing is that we simply simulate a 0 when indeed we need to introduce memory expansion till `offset + 32`.
I'll make a patch to fix this!

**Comment by CPerezz** [comment]
As discussed with @ed255 and @adria0 the memory expansion is what is actually making the test fail.
Setting `gas()` fn to `15_000_000` in the `TestContext` actually allows the test to work.

The main issue is that the reversion for out of gas is not considered in neither the bus-mapping nor the circuits. Since, in fact is not taken into account in the spec yet.

Therefore I added the `T-revert` label to mark it as an issue which depends on the developement of the REVERT implementation first.

**Comment by ChihChengLiang** [comment]
I tried both

```
../target/release/testool --oneliner "call 620a90005100"
../target/release/testool --oneliner "call 620a90015100"
```

On `a807754c0`, they both work. So I think this issue is resolved.
